### ISSUE TITLE
bump up the required version of ExtUtils::ParseXS?

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#172]
This error:

http://www.cpantesters.org/cpan/report/46b82c45-6f58-1014-992d-807f00428581

suggests that we should be bumping up the minimum version of ExtUtils::ParseXS, to overcome errors in older xsubpp.  Perhaps to the version referenced here:  https://metacpan.org/changes/distribution/ExtUtils-ParseXS#L185

**Comment by Leont** [comment]
Can we close this?
