### ISSUE TITLE
ExtUtils-MMUnix parallel make race with .bs files

### ISSUE THREAD

**Issue by nrensen** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#192]
ExtUtils::MakeMaker commit 1364164942c0c55b83e3d48869c7a98c39ecd123 introduced some odd changes:

```
+	$(NOECHO) $(RM_RF) $(BOOTSTRAP)
+	- $(TEST_S) $(BOOTSTRAP) && $(CP) $(BOOTSTRAP) $(INST_BOOT) && \
+	$(CHMOD) $(PERM_RW) $(INST_BOOT)
```

Why remove $(BOOTSTRAP) and then try to copy it? Is that supposed to be:

```+	$(NOECHO) $(RM_RF) $(INST_BOOT)```

Also, why does that commit remove the $(INST_DYNAMIC) dependence on $(BOOTSTRAP)?

```
-$(INST_DYNAMIC): $(OBJECT) $(MYEXTLIB) $(BOOTSTRAP) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVE) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP)
+$(INST_DYNAMIC): $(OBJECT) $(MYEXTLIB) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVE) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP)
```

Using a parallel make (on OpenBSD) I find that this results in a race where the $(BOOTSTRAP) rule is executed in parallel with the $(INST_DYNAMIC) rule and the $(RM_RF) in the $(INST_DYNAMIC) rule can occur in between the following commands during the $(BOOTSTRAP) rule:

```
$(NOECHO) $(TOUCH) %s
$(CHMOD) $(PERM_RW) %s
```

resulting in a build failure:

> Running Mkbootstrap for Compress::Raw::Zlib ()
> rm -f ../../lib/auto/Compress/Raw/Zlib/Zlib.so
> cc  -shared -fPIC  -fstack-protector Zlib.o  adler32.o  compress.o  crc32.o  deflate.o  infback.o  inffast.o  inflate.o  inftrees.o  trees.o  uncompr.o  zutil.o -o ../../lib/auto/Compress/Raw/Zlib/Zlib.so
> chmod 755 ../../lib/auto/Compress/Raw/Zlib/Zlib.so
> chmod 644 Zlib.bs
> /work/OpenBSD/obj/gnu/usr.bin/perl/cpan/Compress-Raw-Zlib/../../miniperl "-I../../lib" "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- Zlib.bs ../../lib/auto/Compress/Raw/Zlib/Zlib.bs 644
> chmod: Zlib.bs: No such file or directory
> *** Error 1 in /work/OpenBSD/obj/gnu/usr.bin/perl/cpan/Compress-Raw-Zlib (Makefile:482 'Zlib.bs')
> *** Error 1 in target 'Zlib.bs'
> Unsuccessful make(cpan/Compress-Raw-Zlib): code=512 at make_ext.pl line 561.

Here's a diff with those two changes applied to current if you agree that it is the right way forward:

```
--- MM_Unix.pm.old	Sun Dec 28 12:12:04 2014
+++ MM_Unix.pm	Sun Dec 28 12:11:50 2014
@@ -932,7 +932,7 @@ OTHERLDFLAGS = '.$ld_opt.$otherldflags.'
 INST_DYNAMIC_DEP = '.$inst_dynamic_dep.'
 INST_DYNAMIC_FIX = '.$ld_fix.'
 
-$(INST_DYNAMIC): $(OBJECT) $(MYEXTLIB) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVEDEP) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP)
+$(INST_DYNAMIC): $(OBJECT) $(MYEXTLIB) $(BOOTSTRAP) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVEDEP) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP)
 ');
     if ($armaybe ne ':'){
 	$ldfrom = 'tmp$(LIB_EXT)';
@@ -984,7 +984,7 @@ MAKE
 
     push @m, <<'MAKE';
 	$(CHMOD) $(PERM_RWX) $@
-	$(NOECHO) $(RM_RF) $(BOOTSTRAP)
+	$(NOECHO) $(RM_RF) $(INST_BOOT)
 	- $(CP_NONEMPTY) $(BOOTSTRAP) $(INST_BOOT) $(PERM_RW)
 MAKE
```

**Comment by mohawk2** [comment]
@nrensen, could you do me a big favour and try out https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179 against the situation you're having a problem with? It reworks the generation of *.bs, among other things.

**Comment by Leont** [comment]
It looks to me like that's a bug. It should delete `$(INST_BOOT)` not `$(BOOTSTRAP)`. Now there will never be a bootstrap file, which is definitely wrong.

**Comment by mohawk2** [comment]
#179 features a test of the *.bs system. Just sayin'.

**Comment by nrensen** [comment]
@mohawk2 Thanks for the fast response. For background, I am building the OpenBSD base system which contains perl 5.20.1 and various modules. The .bs race issue has only occurred in around 6% of builds, not surprising for a race.

Anyway, I replaced v6.98 of ExtUtils-MakeMaker distributed with OpenBSD by the master revision of ExtUtils-MakeMaker and applied https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179. The build failed because one of the generated Makefiles omitted the subdirs_static target.

```
Running Makefile.PL in ext/SDBM_File
../../miniperl -I../../lib Makefile.PL INSTALLDIRS=perl INSTALLMAN1DIR=none INSTALLMAN3DIR=none PERL_CORE=1 LIBPERL_A=libperl.so.17.0 LINKTYPE=dynamic
Generating a Unix-style Makefile
Writing Makefile for sdbm
Generating a Unix-style Makefile
Writing Makefile for SDBM_File
Making all in ext/SDBM_File
/usr/bin/make all PERL_CORE=1 LIBPERL_A=libperl.so.17.0 LINKTYPE=dynamic
"./../../miniperl" "-I../../lib" "../../lib/ExtUtils/xsubpp" -noprototypes -typemap '/work/OpenBSD/obj/gnu/usr.bin/perl/ext/SDBM_File/../../lib/ExtUtils/typemap' -typemap '/work/OpenBSD/obj/gnu/usr.bin/perl/ext/SDBM_File/typemap'  SDBM_File.xs > SDBM_File.xsc && mv SDBM_File.xsc SDBM_File.c
cd sdbm && make all
cc -c  -I../../..  -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -fno-strict-aliasing -fno-delete-null-pointer-checks -pipe -fstack-protector -O2    -DVERSION=\"\"  -DXS_VERSION=\"\" -DPIC -fPIC  "-I../../.."  -DSDBM -DDUFF sdbm.c -o sdbm.o
cc -c  -I../../..  -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -fno-strict-aliasing -fno-delete-null-pointer-checks -pipe -fstack-protector -O2    -DVERSION=\"\"  -DXS_VERSION=\"\" -DPIC -fPIC  "-I../../.."  -DSDBM -DDUFF pair.c -o pair.o
cc -c  -I../../..  -DNO_LOCALE_NUMERIC -DNO_LOCALE_COLLATE -fno-strict-aliasing -fno-delete-null-pointer-checks -pipe -fstack-protector -O2    -DVERSION=\"\"  -DXS_VERSION=\"\" -DPIC -fPIC  "-I../../.."  -DSDBM -DDUFF hash.c -o hash.o
make: don't know how to make subdirs_static (prerequisite of: static)
Stop in /work/OpenBSD/obj/gnu/usr.bin/perl/ext/SDBM_File/sdbm
*** Error 2 in /work/OpenBSD/obj/gnu/usr.bin/perl/ext/SDBM_File (Makefile:1003 'sdbm/libsdbm.a')
*** Error 2 in target
```

Here are links to the source Makefile.PL and generated Makefile:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/gnu/usr.bin/perl/ext/SDBM_File/Makefile.PL?rev=1.9
https://gist.github.com/nrensen/8842942d0472ea0c2a27

For the sake of comparison, I retried with the master revision of ExtUtils-MakeMaker _without_ https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179 which produced the following SDBM_File Makefile:  https://gist.github.com/nrensen/0facb7c316cf570d8a40.
The full OpenBSD build was successful with this version of ExtUtils-MakeMaker, but due to the statistical nature of the issue this doesn't imply that the problem is resolved. I suspect it probably isn't.

In the same way, even had the https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179 build succeeded it wouldn't be strong evidence that the problem was resolved. It would take me a few weeks to accumulate enough builds to be reasonable confident that the problem was resolved. 

Nonetheless, perhaps this is a useful test case for the https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179 code, which appears to have some fallout for the OpenBSD base build at least.

**Comment by mohawk2** [comment]
Speaking of SDBM, could you apply the patch at the bottom of this page against your Perl? It eliminates the static build entirely.

However, I'm still concerned about the lack of subdirs_static target. The Makefile you provide should have in its top_targets section:

```
pure_all :: pure_nolink linkext
        $(NOECHO) $(NOOP)

pure_nolink :: config pm_to_blib subdirs
        $(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
        $(NOECHO) $(NOOP)

subdirs_dynamic ::
        $(NOECHO) $(NOOP)
```

But it doesn't. Is it possible the lower Makefile didn't get regenerated after you replaced EUMM?

**Comment by mohawk2** [comment]
The "this page" I meant was: https://rt.perl.org/Public/Bug/Display.html?id=123413

**Comment by mohawk2** [comment]
@nrensen, I've now adjusted #179 to work with the current SDBM scheme and repushed, so if you try that now it should work.

**Comment by nrensen** [comment]
Wow, you're quick! I applied the SDBM_File patch you linked and started another build, but I'll quit that and try the adjusted https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179. Thanks again.

**Comment by mohawk2** [comment]
Just adjusted what already existed. PR179 needed adjusting since if one module does something that "special", others out there probably do too. Anyway, now you should be able to build with either or both patches.

**Comment by nrensen** [comment]
@mohawk2 OpenBSD base builds successfully with the adjusted PR179. I'll leave that in my tree for a couple of weeks and also build some ports to see if anything shows up.

**Comment by Leont** [comment]
> It would take me a few weeks to accumulate enough builds to be reasonable confident that the problem was resolved. 

I could easily reproduce this issue by adding a `sleep 10` (where 10 seconds is more time than it costs to compile the module) between the `touch` and the `chmod` lines. Patching your MakeMaker to the same effect should tell you quickly if @mohawk2's  branch affects this issue.

**Comment by nrensen** [comment]
Thanks @Leont, good suggestion. Using that approach I confirmed that @mohawk2's branch is immune to that particular race. I will continue to use that branch to see if other things crop up. So far it's working well with a few complete OpenBSD base builds and a variety of perl modules via OpenBSD ports.

A couple of comments about MM_Unix.pm in PR179:

* Why does the `%1$s.bs` rule depend on `$(INST_ARCHAUTODIR)$(DFSEP).exists`?
```
%1$s.bs : $(FIRST_MAKEFILE) $(BOOTDEP) $(INST_ARCHAUTODIR)$(DFSEP).exists
```

* For the sake of clarity, the `%4` (`$basename.bs`) parameter could be dropped in favour of uniform use of `%1$s.bs`? This makes the dependency of the `%3$s` rule on the `%1$s.bs` rule crystal clear and inviolable, which was the subject of this bug report.
```
--- MM_Unix.pm.orig	Fri Jan  2 20:10:06 2015
+++ MM_Unix.pm	Sat Jan  3 11:39:39 2015
@@ -901,8 +901,8 @@
     $instdir = '$(INST_ARCHAUTODIR)' if $basename eq '$(BASEEXT)';
     my $instfile = File::Spec->catfile($instdir, "$f.bs");
     my $exists = File::Spec->catfile($instdir, '.exists');
-    #                             1          2        3          4               5
-    return sprintf <<'MAKE_FRAG', $basename, $target, $instfile, "$basename.bs", $exists;
+    #                             1          2        3          4 
+    return sprintf <<'MAKE_FRAG', $basename, $target, $instfile, $exists;
 # As Mkbootstrap might not write a file (if none is required)
 # we use touch to prevent make continually trying to remake it.
 # The DynaLoader only reads a non-empty file.
@@ -914,9 +914,9 @@
 	$(NOECHO) $(TOUCH) "%2$s"
 	$(CHMOD) $(PERM_RW) "%2$s"
 
-%3$s: %4$s %5$s
+%3$s: %1$s.bs %4$s
 	$(NOECHO) $(RM_RF) %2$s
-	- $(CP_NONEMPTY) %4$s %2$s $(PERM_RW)
+	- $(CP_NONEMPTY) %1$s.bs %2$s $(PERM_RW)
 MAKE_FRAG
 }
 ```

**Comment by mohawk2** [comment]
@Leont, nice work!

@nrensen, both good points! I went further (in the new version of the branch, pushed):

```
-    #                             1          2        3          4               5
-    return sprintf <<'MAKE_FRAG', $basename, $target, $instfile, "$basename.bs", $exists;
+    #                             1          2          3
+    return sprintf <<'MAKE_FRAG', $basename, $instfile, $exists;
 # As Mkbootstrap might not write a file (if none is required)
 # we use touch to prevent make continually trying to remake it.
 # The DynaLoader only reads a non-empty file.
-%1$s.bs : $(FIRST_MAKEFILE) $(BOOTDEP) $(INST_ARCHAUTODIR)$(DFSEP).exists
+%1$s.bs : $(FIRST_MAKEFILE) $(BOOTDEP)
        $(NOECHO) $(ECHO) "Running Mkbootstrap for %1$s ($(BSLOADLIBS))"
        $(NOECHO) $(PERLRUN) \
                "-MExtUtils::Mkbootstrap" \
                -e "Mkbootstrap('%1$s','$(BSLOADLIBS)');"
-       $(NOECHO) $(TOUCH) "%2$s"
-       $(CHMOD) $(PERM_RW) "%2$s"
+       $(NOECHO) $(TOUCH) "%1$s.bs"
+       $(CHMOD) $(PERM_RW) "%1$s.bs"
 
-%3$s : %4$s %5$s
+%2$s : %1$s.bs %3$s
        $(NOECHO) $(RM_RF) %2$s
-       - $(CP_NONEMPTY) %4$s %2$s $(PERM_RW)
+       - $(CP_NONEMPTY) %1$s.bs %2$s $(PERM_RW)
 MAKE_FRAG
```

**Comment by nrensen** [comment]
@mohawk2 Very nice! I've confirmed that the updated PR179 works for a complete OpenBSD base build. The thing I like most is that by eliminating $target you've eliminated the VMS specific code. I spent about a half an hour reading about the VMS MMS in order to understand what was going on with $target previously. This is a big improvement.

Down to nit-picking now, but I think it would be better to remove the quoting from:
```
+       $(NOECHO) $(TOUCH) "%1$s.bs"
+       $(CHMOD) $(PERM_RW) "%1$s.bs"
```
If it's required there, it's also required in the %2$s rule below, but other places throughout EUMM don't appear to quote in similar circumstances and I think it's better to not encourage the use of filenames that require quoting.

**Comment by mohawk2** [comment]
Spaces are valid filesystem characters, and they can occur in circumstances when the user has no control over them (such as `Program Files`). Quite a lot of effort has gone into making EUMM work in those circumstances.

May I suggest that comments on #179 (which are very valuable) go on the comments page for that? Also, if this issue is resolved, could I ask you to "close" it?

**Comment by nrensen** [comment]
I believe this issue is resolved by https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179, but until that has been merged onto the EUMM master this remains an issue for EUMM. I'm a bit surprised it's not affecting more people. Reports of this race started to emerge not long after a version containing the 1364164942c0c55b83e3d48869c7a98c39ecd123 commit was pulled into OpenBSD. @afresh1 has now applied the diff proposed in the original report to settle it down until PR179 or some other fix is released. So I figure that the right time to close this issue is when it is fixed in master. In fact, the protocol in the team in which I earn my crust is that an issue isn't closed until it has been confirmed fixed in a release version. If the protocol here is to close an issue as soon as a fix exists in a pull request then I will close it.

Taking comments on https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/179 to the corresponding comments page.

**Comment by mohawk2** [comment]
FYI, the PR has been merged with master. While I have the access to close this issue, I won't. You're welcome to leave it open until such time as you feel it is resolved.

**Comment by nrensen** [comment]
Thanks for your time on this, @mohawk2.
