### ISSUE TITLE
_eumm/ is put into MANIFEST

### ISSUE THREAD

**Issue by Leont** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#204]
#187 added the `_eumm/` directory. This confuses `make manifest` because it will not be listed in the MANIFEST.SKIP. This is problematic IMO.

**Comment by Leont** [comment]
@karenetheridge your patch solves this issue only for EUMM itself. It doesn't fix it for any other distribution that happens to be using EUMM. `make manifest` will suddenly give an erroneous result if an explicit MANIFEST.SKIP is used, or if they haven't upgraded to ExtUtils::Manifest 1.70.

**Comment by karenetheridge** [comment]
ah,sorry, I misunderstood the ticket :)

doesn't EUMM bundle EUM? how else can it dep on it and call ->manifind etc?

**Comment by Leont** [comment]
> doesn't EUMM bundle EUM? how else can it dep on it and call ->manifind etc?

Ah, I see it does, but that's not enough. It should also be added to `%Extra_prereqs` in the Makefile.PL, for people like me who don't use bundling.

**Comment by karenetheridge** [comment]
> it will still require any dist that has an explicit MANIFEST.SKIP to be updated too

If the user isn't using #!include_default, yes. We should really encourage the use of that more.

I wonder if EUMM shouldn't use the default list internally if there is no MANIFEST.SKIP. It seems silly that every dist has to have one, if the defaults are perfectly adequate. I guess that's an ExtUtils-Manifest issue as this work would be done in ->manifind.

**Comment by Leont** [comment]
> If the user isn't using #!include_default, yes. We should really encourage the use of that more.

Except that #203 makes that a lot less useful that it could be.

> I wonder if EUMM shouldn't use the default list internally if there is no MANIFEST.SKIP. It seems silly that every dist has to have one, if the defaults are perfectly adequate. I guess that's an ExtUtils-Manifest issue as this work would be done in ->manifind.

Module::Build goes through some effort to do just this, I had always assumed ExtUtils MakeMaker did the same :-o

**Comment by mohawk2** [comment]
This PR on EUM makes `#!include_default` much more future-proof: https://github.com/Perl-Toolchain-Gang/ExtUtils-Manifest/pull/17

**Comment by bingos** [comment]
As we rolled back _eumm, I shall close this.
