### ISSUE TITLE
need to add a configure_requires entry for self at 7.05_01 if a version range is seen

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#215]
I used a range here: https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-PromptIfStale-0.041/Makefile.PL#L24

In earlier EUMMs the version range is treated as 0, rather than respecting the stated prereq.

**Comment by karenetheridge** [comment]
reference: https://rt.cpan.org/Ticket/Display.html?id=75758

**Comment by karenetheridge** [comment]
This should happen before 7.06 is released.

**Comment by karenetheridge** [comment]
> This should happen before 7.06 is released.

*bump* 7.05x changes the handling of version ranges. It's important this carry over to the user side.

**Comment by mohawk2** [comment]
@karenetheridge I agree this needs dealing with (cf #252). Would you agree that rather than `7.05_01`, the min version should instead be `7.11_01` since .06-.10 wouldn't be suitable?

**Comment by karenetheridge** [comment]
> Would you agree that rather than 7.05_01, the min version should instead be 7.11_01

I think so, yes.

..although others are making a legitimate case that we don't inject minimum versions when other features are seen (e.g. TEST_REQUIRES)...  So I wonder if a simple warning would instead be sufficient?

warn "hey, you're using this feature, which won't work right before 7.1101, but you're not specifying that minimum version. Are you sure? because that's not going to work very well.";

**Comment by karenetheridge** [comment]
After great reflection I think this is a wrong-headed idea.
