### ISSUE TITLE
Is an emergency revert to 7.04 viable?

### ISSUE THREAD

**Issue by ribasushi** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#236]
Latest EUMM has been part of the stable index for a bit more than a week. During this time it has earned [4 "strikes" (and counting)](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/235). 

How viable it is to make an emergency 7.08 release which is all but reverting back to 7.04 (not sure if 5.22's 7.04_01 is different and needs to be accounted for)?

I'd appreciate if there is no actual bug discussions in this ticket, but rather only pros and cons to the question of rolling things back, while the problems are worked through elsewhere.

To make it clear - I personally think we need to roll back yesterday, therefore :+1: from me.

**Comment by kentfredric** [comment]
:+1: - "Fixes require munging Makefile directly" is very much a "nope, we have to do better, try again" from me.

**Comment by Leont** [comment]
As far as I can tell, the PASSTHRU and VERSION issues are resolved, and the Module-Install-TestTarget issue is solved downstream. Which leaves the "-o" issue.

I want a quick resolution to this issue. Preferably a bug fix release, but it that isn't possible on a shot term a reverting to 7.04_01 (it contains a fix for #193 but is otherwise the same as 7.04) may be the best option.

**Comment by rjbs** [comment]
I'm with @leont.  I'd prefer to push forward, but if that's going to take too long, better to revert to something not suspected to be preventing installs.

**Comment by ribasushi** [comment]
Can we put forward some tangible timeframes, as opposed to the freeform `quick`, `short term` and `too long`? We are talking about a broken installer here...

**Comment by haarg** [comment]
EUMM 7.08 has been released which is a revert to 7.04 except with a few bug fixes applied.

**Comment by ribasushi** [comment]
@bingos ++
Thank you much to all involved!
