### ISSUE TITLE
nmake fails

### ISSUE THREAD

**Issue by nanis** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#239]
I haven't had a chance to diagnose this yet. This is just to get the ball rolling.

<pre> C:\...\ExtUtils-MakeMaker-7.08> perl Makefile.PL
Generating a nmake-style Makefile
Writing Makefile for ExtUtils::MakeMaker
Writing MYMETA.yml and MYMETA.json

C:\...\ExtUtils-MakeMaker-7.08> nmake test

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

makefile(886) : fatal error U1001: syntax error : illegal character '!' in macro
Stop.</pre>

**Comment by Leont** [comment]
Can you look for the line containing the exclamation mark? That should give us a good idea of what's going on.

**Comment by nanis** [comment]
In generated `Makefile`:

<pre>883: ci :
884:	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
885:	  -e "@all = keys %{ maniread() };" \
886:	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all}) == 0 or die qq{$!};" \
887:	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all}) == 0 or die qq{$!};"
</pre>

The use of `$(CI)` indicates the make file indicates to me that we are relying on `nmake` to indeed evaluate expressions starting with `$`. But, it chokes on `$!` because there is no such [`nmake` macro](https://msdn.microsoft.com/en-us/library/cbes8ded.aspx).

[Special Characters in a Makefile](https://msdn.microsoft.com/en-us/library/956d3677.aspx) says, among other things:

> To use the dollar sign (`$`) as a literal character in a command, specify two dollar signs (`$$`). This method can also be used in other situations where `^$` works.

In fact, if I manually change the generated `Makefile` so that the section above now reads:

<pre>ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all}) == 0 or die qq{$$!};" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all}) == 0 or die qq{$$!};"</pre>

the `Makefile` is processed without problems, and `ExtUtils::MakeMaker` builds, but fails tests once again because of the unescaped `$!` (at least those are the ones I was able to catch).

I haven't looked at the source yet, but it looks to me like this would be a simple patch. Feel free to go ahead. I probably won't be able to come back to this before tomorrow.

**Comment by nanis** [comment]
Basically, we need an `nmake` specific version of `MM_Unix::dist_ci` which escapes `$!`, or a branch in in the same function that just replaces `$!` with `$$!` in the returned string if make type is `nmake`.

**Comment by Leont** [comment]
The logic is broken anyway, checking `$!` is only helpful if system returned -1 (couldn't even start process), not when the command itself returns a failure.

And yes, it should have been escaped anyway. I'm not entirely sure why it isn't, oneliner calls quote_literal, which should take care of this.

**Comment by haarg** [comment]
This was broken by 1485eccf36ae7d1078791cbbcdd6eaf78dae14f9 fixed by fad8c46bd41217f7cefc53cfe7b6b35e5d75a84d.  That commit was omitted from EUMM 7.08 though in an effort to deal with other things.

**Comment by nanis** [comment]
<pre>C:\> cpan-outdated|cpanm
--> Working on B/BI/BINGOS/ExtUtils-MakeMaker-7.10.tar.gz
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.10.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.10 ... OK
Building and testing ExtUtils-MakeMaker-7.10 ... OK
Successfully installed ExtUtils-MakeMaker-7.10</pre>
