### ISSUE TITLE
the future of EUMM's development model

### ISSUE THREAD

**Issue by bulk88** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#242]
Deleted as unconstructive -- mst

**Comment by haarg** [comment]
You won't get an exact date when things are going to happen because it doesn't work that way.

You can file PRs against master.  If they are important either for p5p or some other reason, they can be promoted from there to a stable release if master hasn't been stabilized yet.  And p5p always has the ability to apply patches locally if it is needed for development.

**Comment by karenetheridge** [comment]
I believe @haarg already answered these questions in #p5p earlier today:

```
10:49 < bulk88> Is EUMM upstream p5p or upstream cpan now? It looks to me like there was a "fork" for p5p at 7.08.
10:51 < alh> cpan according to corelist
10:52 < bulk88> so why isn't EUMM master in the p5p repo and instead a fork of master?
10:55 < alh> Who what now?
10:55 < bulk88> so do I just send patches to p5p and maintainers.pl customize it? Since if I do a PR on EUMM master on GH, it will never get into p5p.
10:55 <%ether> why do you say it will never get into p5p?
10:55 < alh> p5p doesn't track cpan master repos
10:55 < alh> It tracks cpan releases
10:55 < alh> If whatever's in EUMM's master git hasn't made it into a CPAN release yet, then no, it won't be in p5p
10:56 < alh> That's just how it works
10:56 < bulk88> https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/commit/dedc19de60da7ebad1c3abeecfac8eca3a0cd86c
10:56 < dipsy> [ Releasgineering for v7.08 · Perl-Toolchain-Gang/ExtUtils-MakeMaker@dedc19d · GitHub ] 
10:57 < alh> http://perl5.git.perl.org/perl.git/commitdiff/2b7c926c32b738377e9d68fee7d587c3d43358be ?
10:57 < dipsy> urgh. long url. Try http://tinyurl.com/nqm8cfv
10:57 < dipsy> [ perl5.git.perl.org Git - perl.git/commitdiff ] 
10:59 < bulk88> that is where 7.10 was imported, but I am asking what is the development model of EUMM now, since it isn't what it was 1 year ago
11:02 < alh> https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.10/CONTRIBUTING
11:02 < dipsy> [ CONTRIBUTING - metacpan.org ] 
11:06 < haarg> bulk88: 7.06 had enough issues that it was reverted.  "stable" releases are being made from separate branches until master is stable enough to release again.
11:07 < haarg> p5p still tracks cpan releases and doesn't care about what's in eumm git
11:23 < bulk88> so do I PR the stable branch or master branch on GH?
11:23 < haarg> master
11:24 < bulk88> master will not go into p5p perl this year if ever...
11:25 < bulk88> who is going to the hours fix master?
11:25 < bulk88> *spend
11:45 <%ether> bulk88: best people to poke would be BinGOs and mohawk, on #toolchain
11:45 <%ether> last I heard mohawk was working on the issues in master, but I haven't seen him in a few weeks
11:45 < haarg> there's only one issue remaining that i know of
11:45 < haarg> which is the blib/_eumm thing, which has an easy solution (removing it)
11:46 < haarg> promoting things from master to a stable release is something that can be handled after a change goes into master, if it's important enough
11:47 < haarg> it's also possible to patch eumm directly in blead if it's required for further development, but shipping _ versions of modules in a release is a bad idea
```

Speaking purely as a member of the PTG (I have no special say over EUMM; my comaint bit here is purely to ship emergency fixes) is that we intend to resolve the outstanding issues from the 7.05/7.06 release series over the next month or two, and that will be shipped as 7.11/7.12 from the master branch.  There is certainly no fear of not making a p5p freeze deadline (which isn't at the same time for dual-life modules as it is for blead features, anyway).

**Comment by bulk88** [comment]
<i>While I will obviously read responses of everyone who posts, responses from the general public (no PAUSE EUMM rights), aren't statements from the owner of EUMM (bingos) and his appointed comaints ANDK/CHORNY/ETHER/LEONT/MMML/MSCHWERN/MSTROUT.
</i>

Haarg does not have PAUSE perms over EUMM, he is a random member of the public, he can't speak officially or should I assume Haarg is the owner of EUMM and has the final say on the direction of EUMM and I was mistaken in thinking Bingos is the owner of EUMM?

**Comment by Leont** [comment]
> Haarg does not have PAUSE perms over EUMM, he is a random member of the public, he can't speak officially or should I assume Haarg is the owner of EUMM and has the final say on the direction of EUMM and I was mistaken in thinking Bingos is the owner of EUMM?

BinGOs is the release manager, but in practice most important decisions would likely be made by the broader toolchain gang.

**Comment by bulk88** [comment]
mst so you are taking officially responsibility for EUMM's planning? Are you fine with EUMM being p5p upstream?

**Comment by shadowcat-mst** [comment]
I'm taking responsibility only for shutting this conversation down until it can be restarted with a more constructive and less combative attitude.

**Comment by xdg** [comment]
@bulk88 -- in Berlin we agreed that Toolchain governance issues should be discussed on the cpan-workers mailing list.

I think that you've raised valid concerns about the steering and direction of EUMM.  I'm less interested in having someone make an "official" statement.  But I don't like seeing the git repo appearing schizophrenic about future direction.

I posted your initial ticket there, but I encourage you to write a follow up so the discussion can move there.
