### ISSUE TITLE
Dists with both test files like t/*.t and a test.pl only run test.pl since 7.11_01

### ISSUE THREAD

**Issue by tsibley** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#247]
The generated Makefile used to (as late as 7.10) contain two lines for the `test_dynamic` target, one which ran any specified test files like `t/*.t` and another which ran `test.pl`.

I bisected this to ace8b86c, which is contained by tags v7.11_01, v7.11_02, and v7.11_03.

(On a side note, tags for v7.08 and v7.10 seem missing from the Github repo.)

**Comment by tsibley** [comment]
Simple test dist here: http://tsibley.net/paste/2015-12-01YeZl8zTT-eumm-regression-test-case.tar.gz

Bisected with:

```sh
tar xzvpf eumm-regression-test-case.tar.gz -C /tmp
git bisect start master v7.04
git bisect run bash -c '(cd /tmp/eumm && perl -Mlib=$HOME/src/ExtUtils-MakeMaker/lib/ Makefile.PL && make test >output 2>&1 && grep "test in t/" output && grep "test in test.pl" output)'
```

Note that 7.10 is known good, but there's no tag for it so I bisected using 7.04.  I first noticed this issue because of missing test output from Andreas' smokers which are running 7.11_03.

**Comment by tsibley** [comment]
ace8b86 is the commit which fixed a regression noted in https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/235, FWIW.

**Comment by Leont** [comment]
Yeah, that `elsif` is clearly wrong.

**Comment by mohawk2** [comment]
I'll make a PR for this shortly.
