### ISSUE TITLE
dos2unix() does not work on Windows

### ISSUE THREAD

**Issue by ribasushi** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#258]
It splits on `\n`, then uses the default IO layer for the OS to write back `\r\n` to the actual files. [This is the workaround](https://github.com/dbsrgits/dbix-class/blob/master/Makefile.PL#L228-L236) I have been using for ~2 years, would be nice to get this fixed in-core.

**Comment by Leont** [comment]
The existent code is rather surprising. Two simple binmodes should fix this, really.

(Also, `$ENV{PERLIO}='perlio'` would be a more logical workaround, it should give the same effect but not kill buffering)

**Comment by bingos** [comment]
Closing now 7.12 is out with the fix.
