### ISSUE TITLE
EU::MM 7.12 breaks CSS::Sass

### ISSUE THREAD

**Issue by mgreter** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#274]
Hello

This was originally reported at https://github.com/sass/perl-libsass/issues/25

I have tried to debug it but have hit some other obstacles on the road. Therefore I'm positing this here, in the hope somebody can give me more hints how to address this properly. I also saw that about 3 tickets on the [cpan bug tracker] [1] reported something similar, but unsure if they are directly related.

The reason it started to fail is the difference in the following two lines:
```bash
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong libsass/src/*.o Sass.o -lstdc++ -o blib/arch/auto/CSS/Sass/Sass.so # EU::MM 7.10
x86_64-linux-gnu-gcc -shared -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/CSS/Sass/Sass.so -lstdc++ libsass/src/*.o Sass.o # EU::MM 7.12
```
The problem is really seems to be the order of `-lstdc++` vs  `libsass/src/*.o`

I'm not sure why these should produce different results, but they unfortunately do. My tests indicate that it works if the `-lstdc++` option comes after at least the first object file, but it fails if it is added before. 

The `-lstdc++` flag is directly from ExtUtils::CppGuess (`{'dynamic_lib'}->{'OTHERLDFLAGS'}`). I saw from the generated Makefile that this flag would work if it would have been in `$LDLOADLIBS` or `$INST_DYNAMIC_FIX`. Next I tried to move the detected `OTHERLDFLAGS` directly to `LIBS`, but then I get `Warning (mostly harmless): No library found for -lstdc++`.

After a bit more debugging I found that my `libpth` (from Config) seems wrong:
```
# perl -e 'use Config; use Data::Dumper; print Dumper(\%Config)' | grep "'\(libspath\|libpth\|incpth\)"
'incpth' => '/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include-fixed /usr/include',
'libpth' => '/usr/local/lib64 /lib64 /usr/lib64 /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include-fixed /usr/lib /lib/../lib64 /usr/lib/../lib64 /lib',
'libspath' => ' /usr/local/lib64 /lib64 /usr/lib64 /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include-fixed /usr/lib /lib/../lib64 /usr/lib/../lib64 /lib',
```
```bash
# perl -e 'require ExtUtils::Liblist; ExtUtils::Liblist->ext("-lstdc++", 1, 1);'
Potential libraries are '-lstdc++':
stdc++ not found in /usr/local/lib64
stdc++ not found in /lib64
stdc++ not found in /usr/lib64
stdc++ not found in /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include-fixed
stdc++ not found in /usr/lib
stdc++ not found in /lib/../lib64
stdc++ not found in /usr/lib/../lib64
stdc++ not found in /lib
Warning (mostly harmless): No library found for -lstdc++
```

So this seem like an other upstream bug (I also found a few [other post] [2] that seem to have this problem). Maybe somebody could verify (might be a gentoo specific problem)? Otherwise it seems that this should be reported somehwere upstream.

Anyway, sorry if this report is a bit of a mess, but the only way to fix the issues with CSS::Sass and EU::MM 7.12+ I see, is to actually tamper with the produced Makefile, which I really would like to avoid.

Thanks and best regards
Marcel Greter

Edit: Probably should have mentioned that my compilers adds `-Wl,--as-needed`, which explains why the two lines from above behave different (in my case it seems to be added by EUMM itself AFAICS).

[1]: http://comp.lang.perl.misc.narkive.com/0vhZHeZJ/libstdc-problem-with-extutils-makemaker
[2]: https://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-MakeMaker

**Comment by mgreter** [comment]
One workaround fthat seems to work at least in my case:
```perl
my $guess = ExtUtils::CppGuess->new();
my %compiler_flags = $guess->makemaker_options();
if (exists $compiler_flags{'dynamic_lib'}) {
  my $dlibs = $compiler_flags{'dynamic_lib'};
  if (exists $dlibs->{'OTHERLDFLAGS'}) {
    $dlibs->{'OTHERLDFLAGS'} = join " ",
      '-Wl,--no-as-needed',
      $dlibs->{'OTHERLDFLAGS'},
      '-Wl,--as-needed';
  }
}
```

**Comment by Leont** [comment]
I pushed a possible fix to the otherldflags branch, can you check if it fixes your issue?

**Comment by mohawk2** [comment]
It seems like this would be easy enough to make a test for to avoid future moving away from this?

**Comment by mgreter** [comment]
@Leont A short test seem to indicate that this also fixes the problem.
You should be able to test yourself with `cpan OCBNET/CSS-Sass-3.3.5`
Do you guys have any advice how I should handle this in regard to the already published EU::MM versions? Do you see any drawback with the workaround I posted earlier?

**Comment by Leont** [comment]
> Do you guys have any advice how I should handle this in regard to the already published EU::MM versions?

You could use a version range there. I believe on old EUMM that would be interpreted as a `0` dependency (which is fine), and on recent ones it will be correctly interpreted.

**Comment by mgreter** [comment]
It looks like the patch is included in EUMM 7.20?
Therefore I guess this issue can be closed?
FWIW here the final patch I added to my [Makefile.PL] [1].

```pl
# Fix an issue with EU::MM > 7.10 as reported in:
# https://github.com/sass/perl-libsass/issues/25
my $EMMV = $ExtUtils::MakeMaker::VERSION;
# Bug has been fixed in version 7.20
if ($EMMV > 7.10 && $EMMV < 7.20) {
  # Fix another issue if as-needed is not supported
  # https://github.com/sass/perl-libsass/issues/26
  unless (`ld --help` =~ m/--no-as-needed/) {
    warn "Your current ExtUtils::MakeMaker has a bug\n";
    die "You need to upgrade ExtUtils::MakeMaker to 7.20+\n";
  }
  if (exists $compiler_flags{'dynamic_lib'}) {
    my $dynlibs = $compiler_flags{'dynamic_lib'};
    if (exists $dynlibs->{'OTHERLDFLAGS'}) {
      if ($guess->is_gcc) {
        $dynlibs->{'OTHERLDFLAGS'} = join " ",
          '-Wl,--no-as-needed',
          $dynlibs->{'OTHERLDFLAGS'},
          '-Wl,--as-needed';
      }
    }
  }
}
```

[1]: https://github.com/sass/perl-libsass/blob/develop/Makefile.PL#L308-L330

**Comment by dolmen** [comment]
@mgreter Add an eval to your $EMMV assignment. Because $VERSION may be a development version with an '_'.

```perl
my $EMMV = eval $ExtUtils::MakeMaker::VERSION;
```

**Comment by Leont** [comment]
> Add an eval to your $EMMV assignment. Because $VERSION may be a development version with an '_'.

I don't think that's necessary, as dev-versions are only problematic when doing equality comparing.

**Comment by haarg** [comment]
At least in the case of MakeMaker that should be true, although they will still produce warnings.

**Comment by dolmen** [comment]
EUMM 6.55_02 is [bundled with perl 5.10.1](https://metacpan.org/source/DAPM/perl-5.10.1/lib/ExtUtils/MakeMaker.pm#L21) and does not have the `$VERSION = eval $VERSION;` line. So @mgreter's code would trigger a warning `Argument "6.55_02" isn't numeric in numeric gt (>)`. Isn't it?

**Comment by mgreter** [comment]
@all thanks for the heads up. I remember that I tried to reasearch how to parse and also how to define version numbers a few years ago (I only started to maintain a few CPAN modules). AFAIR some examples used quoted strings and others added the notion of the underscore to indicate beta/alpha versions (I guess the later is only supported by "newer" perl versions?). Honestly I'm still not sure how to correctly define/release a beta version on CPAN. I had some sorting issues (still visible at http://matrix.cpantesters.org/?dist=CSS-Sass) with some versions (CSS-Sass v3.0.1_3 is listed before CSS-Sass v3.0.2). 
 
@dolmen I wonder (simply don't know) why eval will work in this case? I would probably prefer a solution using regex before relying/allowing an eval. But I also dont see exactly why the `eval $VERSION` will yield a "valid" result. I would be thankfull if you could point me in the right direction :)

Anyway, thanks for all your input!

**Comment by haarg** [comment]
Numbers in perl are allowed to have underscores in them, which are ignored when parsing.  This is to let you format the numbers for easier reading.  `my $num = 1_000_000;` for example.  This doesn't apply to quoted numbers.  The eval will evaluate the version as an unquoted number, so the result will not have the underscores.

Other options would be do `$EUMM =~ tr/_//d;` or `$EUMM =~ s/_//g;`.

For beta versions of modules using numeric version, you can define a version like `our $VERSION = "3.001_002";`.  However, if you are using dotted-decimal style versions (which you are), then it is instead recommended you use -TRIAL releases.  This simply means naming the uploaded tarball like `CSS-Sass-v3.0.3-TRIAL.tar.gz`.

**Comment by mgreter** [comment]
Thx for the info, I guess for me a regex like `$EMMV =~ m/\A7.1[1-9](?:\z|\.)/` should also work then ...
