### ISSUE TITLE
Make it easier to say "OS not supported"

### ISSUE THREAD

**Issue by neilb** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#298]
Last week I had to, not for the first time, try and remember / find the special string you exit from Makefile.PL with if the OS isn't supported. Ie this:

    die "No support for OS\n" if $^O eq 'MSWin32';

At the very least this needs to documented somewhere, but more than that, how about EUMM providing one or more convenience functions, so people don't have to embed that string?a

This could be something like:

    os_not_supported('MSWin32');
    os_restriction('MSWin32');

Haven't really thought much about the interface -- I wanted to raise the ticket before I forgot about this.

I guess it would be in a separate package, so Build.PL could use it as well...

**Comment by bingos** [comment]
Implemented as os_unsupported() with commit fcdaaac274c747e4f573d51b631c5f416ecca5e6

**Comment by Leont** [comment]
> Implemented as os_unsupported() with commit fcdaaac

It really should document "supported since 7.26"

**Comment by bingos** [comment]
Done

**Comment by ap** [comment]
Calling that function from Makefile.PL requires `configure_requires` support. Is that worth it for being able to spell `die "OS unsupported\n"` as `os_supported`? 😐

**Comment by karenetheridge** [comment]
Of course not. But in 20 years, when everyone has this version of EUMM in core, we'll sure be happy we have it. 👯‍♂️ 

(sarcasm)

**Comment by ap** [comment]
Fear not: the clock started 5 years ago when 5.14 shipped with working `configure_requires`, so it’s only 15 years from now. 😊

**Comment by mohawk2** [comment]
Can this issue be closed now?
