### ISSUE TITLE
erlsvc regression: No rule to make target 'test_dynamic'

### ISSUE THREAD

**Issue by ntyni** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#305]
Recent versions of EU::MM seem to have broken the [erlsvc](https://github.com/rbalint/erlsvc) build. It now fails at 'make test' with

> % make test
> make[1]: Entering directory '/home/niko/tmp/erlsvc/share'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/niko/tmp/erlsvc/share'
> make[1]: Entering directory '/home/niko/tmp/erlsvc/share'
> make[1]: *** No rule to make target 'test_dynamic'.  Stop.
> make[1]: Leaving directory '/home/niko/tmp/erlsvc/share'
> Makefile:937: recipe for target 'subdirs-test_dynamic' failed
> make: *** [subdirs-test_dynamic] Error 2

This was observed while test rebuilding Debian packages with Perl 5.26.0. The test suite works fine with 5.24.

I've tested that this still happens with current EU::MM as of commit 565c2df4185cb51ddb035d10245878d12c5d6649. I've bisected that this regressed with 0c38f3739cb7476fc1b843484584fee30c9ea69e.

We haven't seen similar failures in other packages. Is erlsvc doing something unsupported here?

**Comment by Leont** [comment]
MakeMaker is expecting all recursive Makefile.PLs to have `test_dynamic` target in recent versions of MakeMaker, where old versions would use `test`. The Makefile.PL In `share/` is entirely custom instead of using MakeMaker, so it doesn't have this new target. The quick fix would be to add it as a noop (as `test` already is).

**Comment by karenetheridge** [comment]
share/Makefile.PL can go away entirely with the proper use of
File::ShareDir::Install in the top level Makefile.PL -- and I'd remove the
use of Module::Install at the same time because of broken compatibility
with the newest perl (no . in @INC), and the lack of modern META support.

**Comment by Leont** [comment]
> share/Makefile.PL can go away entirely with the proper use of File::ShareDir::Install in the top level Makefile.PL

It would also need a `postamble`, for compiling the `.erl`s to `.beam`.

**Comment by jmdh** [comment]
Thanks, we've passed these suggestions onto the Debian maintainer of erlsvc.

**Comment by rbalint** [comment]
Thanks All, I rewrote Makefile.PL-s in erlsvc.
