### ISSUE TITLE
MakeMaker dynamic section generated not proper cause compile failed when make with multi jobs

### ISSUE THREAD

**Issue by sandy-lcq** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#328]
Hi,

This problem  is very hard to reproduce,  but it really did happened. I met 2 times,  one is
package  html-parser  and one is package Text-Iconv. And these two should caused by one
problem.

Here is related log:
1. for package html-parser  which use MakeMaker.
chmod 755 blib/arch/auto/HTML/Parser/Parser.so 
chmod 644 "Parser.bs" 
perl -MExtUtils::Command::MM -e 'cp_nonempty' -- Parser.bs blib/arch/auto/HTML/Parser/Parser.bs 644 
chmod: cannot access 'Parser.bs': No such file or directory 
Makefile:485: recipe for target 'Parser.bs' failed
2.  for package Text-Iconv  which use MakeMaker.
chmod 755 blib/arch/auto/Text/Iconv/Iconv.so 
chmod 644 "Iconv.bs" 
perl -MExtUtils::Command::MM -e 'cp_nonempty' -- Iconv.bs blib/arch/auto/Text/Iconv/Iconv.bs 644 
chmod: cannot access 'Iconv.bs': No such file or directory 
make: *** [Makefile:451: Iconv.bs] Error 1 

This problem should happen when Make with multi jobs,  I use make -j 48.

I analysed Makefile generated by  MakeMaker,  I think below part is not proper for multi jobs:

--- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(BOOTSTRAP) $(INST_DYNAMIC)
        $(NOECHO) $(NOOP)

seems dynamic have 3 target, ${BOOTSTRAP} will create Parser.bs and chmod of  Parser.bs, ${INST_DYNAMIC} have action "rm -rf Parser.bs" .  so there is possible when multitask run, 
target ${INST_DYNAMIC}  delete the  Parser.bs which just create by ${BOOTSTRAP}, then chmod action in ${BOOTSTRAP} will failed since no such file.

should target $(BOOTSTRAP)  and target $(INST_DYNAMIC)  have kinds of dependency to avoid this
problem? Please help to check, thanks.

Here is the Makefile of  package html-parser, maybe help for debug:
[Makefile.zip](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/files/2370081/Makefile.zip)

**Comment by mohawk2** [comment]
Hi, thanks for the report. The `Makefile` you attach shows it's generated by EUMM v7.10. The latest released version is 7.34. Could you try this with the latest released (and if possible also with the latest dev-release or even `master` version) and see if this is still the case?

**Comment by mohawk2** [comment]
By the way, looking at `MM_Any`, I agree that `INST_BOOT` should probably depend off `INST_DYNAMIC` rather than off `dynamic`.

**Comment by sandy-lcq** [comment]
It is hard to reproduce,  cannot reproduce even with EUMM v7.10.  But I tried with V7.34,  from the generated makefile,  should still have same problem. maybe MM_Any should be changed like you 
said.  

Here is the makefile of V7.34
[Makefile.zip](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/files/2373401/Makefile.zip)

**Comment by mohawk2** [comment]
Thanks. The previous (7.10) Makefile had this section:

```
$(INST_DYNAMIC): $(OBJECT) $(MYEXTLIB) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVEDEP) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP)
	$(RM_F) $@
	$(LD)  $(LDDLFLAGS) $(LDFROM) $(OTHERLDFLAGS) -o $@ $(MYEXTLIB)	\
	  $(PERL_ARCHIVE) $(LDLOADLIBS) $(PERL_ARCHIVE_AFTER) $(EXPORT_LIST)	\
	  $(INST_DYNAMIC_FIX)
	$(CHMOD) $(PERM_RWX) $@
	$(NOECHO) $(RM_RF) $(BOOTSTRAP)
	- $(CP_NONEMPTY) $(BOOTSTRAP) $(INST_BOOT) $(PERM_RW)
```

which as you say did delete the `$(BOOTSTRAP)`. The 7.34 one has this:

```
$(INST_DYNAMIC) : $(OBJECT) $(MYEXTLIB) $(INST_ARCHAUTODIR)$(DFSEP).exists $(EXPORT_LIST) $(PERL_ARCHIVEDEP) $(PERL_ARCHIVE_AFTER) $(INST_DYNAMIC_DEP) 
	$(RM_F) $@
	$(LD)  $(LDDLFLAGS)  $(LDFROM) $(OTHERLDFLAGS) -o $@ $(MYEXTLIB) \
	  $(PERL_ARCHIVE) $(LDLOADLIBS) $(PERL_ARCHIVE_AFTER) $(EXPORT_LIST) \
	  $(INST_DYNAMIC_FIX)
	$(CHMOD) $(PERM_RWX) $@
```

which no longer does. Therefore EUMM no longer does the thing you're concerned about. Would you agree this can now be closed?

**Comment by sandy-lcq** [comment]
Thanks.  I agree with you.   I did't notice this  change yesterday.  This can be closed.
