### ISSUE TITLE
Test failures on AIX for LibList Kid

### ISSUE THREAD

**Issue by bingos** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#344]
https://www.cpantesters.org/cpan/report/1b4f6156-0722-11ea-9066-e374b0ba08e8

Test failures in t/Liblist_Kid.t

On AIX the following are set:
$ /pro/bin/perl -V:lib_ext -V:so -V:dlext
lib_ext='.a';
so='a';
dlext='so';

Apparently on AIX .a can be static and shared.

Whether the library is dynamic is determined here:
https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/master/lib/ExtUtils/Liblist/Kid.pm#L213

And added to LD_RUN_PATH here (if it is dynamic):
https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/master/lib/ExtUtils/Liblist/Kid.pm#L219

The test is using the value of $Config{so}:
https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/master/t/Liblist_Kid.t#L95

So this creates libfoo.a which is determined to be non-dynamic which ultimately causes the test failures.

Perhaps instead of using 'so' we should be using 'dlext' ????

**Comment by Leont** [comment]
> Apparently on AIX .a can be static and shared.

Typical…

> The test is using the value of $Config{so}:
> Perhaps instead of using 'so' we should be using 'dlext' ????

I don't think so, but @Tux is the expert

**Comment by Tux** [comment]
```
aix> perl -V:'dlext|so'
dlext='so';
so='a';
```
`static` builds are rare on AIX. Almost everything is shared by default.
Much worse than `.a` can be shared or static, is that they can have both 32bit objects and 64bit objects, and you need flags or environment variables to see that. An archive may look empty (for the current build environment) even if it is not, so removing an archive because it looks empty is seldom a good idea.
```
$ ls -l liby.a
-rw-r--r-- 1 merijn softwr 3078 Aug  8  2018 liby.a
$ ar -X 32 tv liby.a
$ ar -X 64 tv liby.a
rw-r--r--   203/200     1171 Aug 08 09:26 2018 main.o
rw-r--r--   203/200     1159 Aug 08 09:26 2018 yyerror.o
$ env OBJECT_MODE=32 ar tv liby.a
$ env OBJECT_MODE=64 ar tv liby.a
rw-r--r--   203/200     1171 Aug 08 09:26 2018 main.o
rw-r--r--   203/200     1159 Aug 08 09:26 2018 yyerror.o
```
IIRC `.a` is used as a library for linking and `.so` is used as shared loadable object.

**Comment by Leont** [comment]
> static builds are rare on AIX. Almost everything is shared by default.

Sounds like we should always assume it's a dynamic library on AIX. That sounds like a pretty simple solution actually.
