### ISSUE TITLE
Best Practice for mandating a minimum version for an optional module

### ISSUE THREAD

**Issue by pmqs** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#345]
I need some advice on how to mandate the minimum version of another module, but only when that module is already installed.

This logic is needed for the module, https://github.com/pmqs/Archive-Zip-SimpleZip, where the `Makefile.PL` includes the equivalent to this this in the `META_MERGE` section.

```
prereqs => {
    runtime => {
	requires => {
	    'IO::Compress::Base'   =>  2.091,
	},
	recommends => {
	    'IO::Compress::Lzma'     =>  2.091,
	},
    },  
```

I had hoped that `recommends` would fail the build immediately if `IO::Compress::Lzma` was less than 2.091, but looking at some of the cpantesters failures, it is allowing older versions of `IO::Compress::Lzma` to exist. I then get failures in the module test harness.

I can easily  add code to `Makefile.PL` to dynamically add `IO::Compress::Lzma` to the `requires` list if it finds it installed, but is that the way to proceed here?

The part I'm not clear on is how a dynamic `requires` list  interacts with the rest of the toolchain involved in smokers/cpanm etc.

Is there a best-practice for dealing with is kind of dependency?

**Comment by Grinnz** [comment]
Yes, this would be a dynamic requirement if you find that the module is installed. See here for an example: https://metacpan.org/source/HAARG/JSON-MaybeXS-1.004000/Makefile.PL#L78-83

As long as you do not declare dynamic_config: 0 or x_static_install: 1, then all prerequisites are dynamic other than the configure phase. Only what is generated in MYMETA.json by Makefile.PL is canonical for the other phases. All of the core toolchain understands this.

**Comment by pmqs** [comment]
Excellent. Thank you.

What should I ship in META.json/jml, or does it matter?

**Comment by Grinnz** [comment]
What you ship in META.json mostly matters for display on MetaCPAN and similar dependency analysis. It's up to you whether you consider it a "dependency" or more of a workaround.

**Comment by pmqs** [comment]
OK, got it.

Appreciate the swift response.

**Comment by haarg** [comment]
Note that dynamic prereqs must be provided through `PREREQ_PM`, `BUILD_REQUIRES`, or `TEST_REQUIRES`.  They cannot be provided through `META_ADD` or `META_MERGE`.  The `META_*` sections are ignored on user machines.  They are only able to impact the `META.yml` and `META.json` files generated by `make distdir` or `make dist`.

**Comment by pmqs** [comment]
Thanks @haarg. 

I see that https://metacpan.org/source/HAARG/JSON-MaybeXS-1.004000/Makefile.PL does the  usual version number dance to decide when it can use  `PREREQ_PM`.

**Comment by Grinnz** [comment]
In general, it's best to specify all your runtime requirements in PREREQ_PM regardless of version. Only use META_MERGE to specify things EUMM cannot handle itself, such as runtime recommends or develop requires. Incidentally there is no way to specify dynamic runtime recommends, for example.

**Comment by pmqs** [comment]
> ... Incidentally there is no way to specify dynamic runtime recommends, for example.

You mean without conditionally writing `PREREQ_PM`  in Makefile.PL (like  `JSON-MaybeXS` does)?

**Comment by Grinnz** [comment]
I'm not sure what you're referring to, JSON-MaybeXS does not conditionally write PREREQ_PM.

**Comment by haarg** [comment]
There is no way to specify dynamic runtime **recommends**.  This is because the only way to specify that type of prereq is through `META_ADD` or `META_MERGE`, which are both ignored on the end user's machine.  `PREREQ_PM` can be set dynamically, like `JSON-MaybeXS` does, but that is a runtime **requires** relationship.

**Comment by pmqs** [comment]
> I'm not sure what you're referring to, JSON-MaybeXS does not conditionally write PREREQ_PM.

This is what I was thinking of in the `Makefile.PL` from `JSON-MaybeXS` .

```
  $MM_ARGS{PREREQ_PM}{'JSON::XS'} = '3.00'
    if eval { require JSON::XS; 1 }
      and not eval { JSON::XS->VERSION('3.0'); 1 };
...
$MM_ARGS{PREREQ_PM} = {%{$MM_ARGS{PREREQ_PM}}, %{delete $MM_ARGS{BUILD_REQUIRES}}}
  if $eumm_version < 6.55_01;
```

**Comment by pmqs** [comment]
> There is no way to specify dynamic runtime **recommends**. This is because the only way to specify that type of prereq is through `META_ADD` or `META_MERGE`, which are both ignored on the end user's machine. `PREREQ_PM` can be set dynamically, like `JSON-MaybeXS` does, but that is a runtime **requires** relationship.

Thanks

**Comment by Grinnz** [comment]
The first of those is setting the dynamic requirement that I was referring to. The second is adding build and test requirements to PREREQ_PM when EUMM is too old to support those separate keys, and has nothing to do with populating PREREQ_PM itself.
