### ISSUE TITLE
oneliner helper does not allow variables

### ISSUE THREAD

**Issue by atoomic** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#355]
When reading the unit test for the `sub oneliner` from `t/oneliner.t`
```
try_oneliner(q{$PATH = 'foo'; print $PATH},[], q{foo},   'dollar signs' );
```

You have the feeling that oneliner authorizes the usage of variables, all the most the test is passing.
But in truth it's using references:
```
# $(ABSPERLRUN)  -e '$$PATH = '\''foo'\''; print $$PATH' --
```

I wonder if we should teach `sub oneliner` to `allow_variables` when calling `quote_literal`, or detect incorrect usage of variable...

For example you can use `%h` but then it's going to fail when using `$h` later to access a value... 

Detail:
====
`my %h = (1..4);` is a valid oneliner
```
$mm->oneliner( q[my %h = (1..4);]);
# $(ABSPERLRUN)  -e 'my %h = (1..4); print $$h[1]' --
```

but `my %h = (1..4); print $h[1]` is invalid
```
$mm->oneliner( q[my %h = (1..4);]);
# $(ABSPERLRUN)  -e 'my %h = (1..4); print $$h[1]' --
```

```perl
#!perl

use Test::More;

require ExtUtils::MM;

my $mm = MM->new(
	{ NAME => q[Fake], }
);

my $cmd;

# valid - using ref
my $cmd = $mm->oneliner( q[$PATH = 'foo'; print $PATH]);
note $cmd;
# $(ABSPERLRUN)  -e '$$PATH = '\''foo'\''; print $$PATH' --

# invalid
my $cmd = $mm->oneliner( q[my $PATH = 'foo'; print $PATH]);
note $cmd;
# $(ABSPERLRUN)  -e 'my $$PATH = '\''foo'\''; print $$PATH' --

```

**Comment by Leont** [comment]
>  But in truth it's using references:

What are you talking about? That looks like a oneliner correctly escaped to be used in a Makefile.

**Comment by atoomic** [comment]
`$mm->oneliner( q[$PATH = 'foo'; print $PATH] );` converts to `'$$PATH = '\''foo'\''; print $$PATH'`
so this is working fine when not doing something else than that kind of `$` usage... 
`$$PATH` is a reference to a SV

proof in image
```
╰─> perl -e '$$a = 42; use Devel::Peek; Dump $a; print $$a'
SV = IV(0x7f879c024f00) at 0x7f879c024f10
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x7f879c00ade0
  SV = IV(0x7f879c00add0) at 0x7f879c00ade0
    REFCNT = 1
    FLAGS = (IOK,pIOK)
    IV = 42
42%
```

**Comment by Leont** [comment]
Given this Makefile
```make
all:
    perl -e '$$a = 42; use Devel::Peek; Dump $$a'
```

Try running `make`

**Comment by atoomic** [comment]
Another way to show the problem is to add a simple `my` before `$PATH = 'foo'; print $PATH`
`$mm->oneliner( q[my $PATH = 'foo'; print $PATH] );`
which convert the code to
`# $(ABSPERLRUN)  -e 'my $$PATH = '\''foo'\''; print $$PATH' --`
which is invalid Perl code... as shown just after
```
╰─> perl -e 'my $$PATH = '\''foo'\''; print $$PATH'
Can't declare scalar dereference in "my" at -e line 1, near "$PATH ="
Execution of -e aborted due to compilation errors.
```

**Comment by atoomic** [comment]
another example is to  try one liner using a simple hash
`my %h = (1 => 2); print $h{1};`
will then convert to 
`# $(ABSPERLRUN)  -e 'my %h = (1 => 2); print $$h{1}; ' --`
which is not running what we think should run

**Comment by Grinnz** [comment]
As @Leont said this is not generating Perl code, it is generating Perl code escaped for use in a Makefile.

**Comment by atoomic** [comment]
Thanks for the clarification, once used in a Makefile, there is no issue.

Unfortunately the unit test `t/oneliner.t` is not consuming it via a Makefile, which explains the confusion.

view https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/blob/master/t/oneliner.t#L33

**Comment by mohawk2** [comment]
@atoomic You are asserting as fact that `perl -E 'say $$x'` **in a Makefile recipe** ends up as dereferencing a scalar. Read the documentation for make and how it interprets `$` in its recipes.

**Comment by mohawk2** [comment]
The `oneliner` function is only supposed to produce things for use in a Makefile. Surely this is not that baffling an idea in a module called "MakeMaker".

**Comment by atoomic** [comment]
My main concern is the way we perform the test `t/oneliner.t` and leads to use references.
I've no problem with the double escaping itself which is required for Makefile syntax.

Please view and consider https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/356

**Comment by atoomic** [comment]
a simple test like `my $x` in `t/oneliner.t` will show the issue, you can for example add a simple `my` when testing the oneliner function:
`try_oneliner(q{my $PATH = 'foo'; print $PATH},[], q{foo},   'dollar signs' );`

which will lead to this error
```
t/oneliner.t ..
1..16
ok 1 - use ExtUtils::MM;
ok 2 - An object of class 'MM' isa 'ExtUtils::MakeMaker'
ok 3 - An object of class 'MM' isa 'ExtUtils::MM_Any'
ok 4 - quotes
Can't declare scalar dereference in "my" at -e line 1, near "$PATH ="
Execution of -e aborted due to compilation errors.
not ok 5 - dollar signs

#   Failed test 'dollar signs'
#   at t/oneliner.t line 41.
#          got: ''
#     expected: 'foo'
# oneliner:
# "/Users/nicolas/perl5/perlbrew/perls/perl-5.30.1/bin/perl"  -e 'my $$PATH = '\''foo'\''; print $$PATH' --
```
