### ISSUE TITLE
Travis isn't testing what you think it's testing.

### ISSUE THREAD

**Issue by toddr** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#359]
If you look at some of the output, you'll see that travis is, for instance, it's not actually testing 5.8.7. If you look closer, I think you'll find that nothing below 5.14 is currently being smoked in Travis. 

https://travis-ci.org/github/Perl-Toolchain-Gang/ExtUtils-MakeMaker/jobs/712741735

I can provide you a .github CI if you prefer that would look something like this https://github.com/toddr/IPC-Run/tree/master/.github/workflows

Note that it only tests 5.8, not 5.8.7

**Comment by karenetheridge** [comment]
The job you linked is indeed testing 5.8.7. See at line 232 of the output it actually compiles that perl first, and then at line 245 prints  the `perl -V` output which is correct.
