### ISSUE TITLE
Shebang handling is nice, but without script renaming, you cannot install modules in two Perl versions simultaneously

### ISSUE THREAD

**Issue by matthewpersico** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#383]
I've read a bunch of issues here and I cannot tell if this is covered or not.

- Situation
I have two versions of Perl installed on my machine. One is the production version, the other is for testing and upgrade. (For completeness the versions involved are 5.16 and 5.32.) 5.16 happens to be the default, such that `/opt/other/bin/perl` is a link to `/opt/other/bin/perl5.16` and similarly for all the scripts packaged with Perl.

- Problem
That doesn't happen with modules. I install perltidy under Perl 5.16 and I get a file `/opt/other/bin/perltidy` whose shebang line is `#!/opt/other/bin/perl5.16`. I then install perltidy under Perl 5.32 and I get a file `/opt/other/bin/perltidy` whose shebang line is `#!/opt/other/bin/perl5.32`.

- Goal
The ability to tell EU::MM to do what Perl does and add the version to the end of all scripts installed by a module. The result of installing perltidy twice as above would be two files:

    /opt/other/bin/perltidy5.16
    /opt/other/bin/perltidy5.32

with appropriate shebang lines.

**Comment by Grinnz** [comment]
I would consider it an error to configure two different versions of Perl with the same installsitescript dir. Surely they already have separate installsitelib and etc?

**Comment by matthewpersico** [comment]
So you are suggesting that I can do `perl Makefile.PL INSTALLSITEBIN=/opt/myjob/share/perl5/site_perl/5.16/bin`?
Or even better, when I build Perl, `configure -D INSTALLSITEBIN=$(PREFIX)/lib/perl5/site_perl/5.16/bin`?
Interesting. Do modules' scripts get installed to INSTALLSITEBIN by default? I guess they would have to; modules are installed to the site location.

So, if I did this, I would have to still arrange for a link in /opt/myjob/bin to point to all these installations, e.g.; `/opt/myjob/bin/perltidy5.16 -> 
/opt/myjob/share/perl5/site_perl/5.16/bin/perltidy` and 
`/opt/myjob/bin/perltidy5.32 -> 
/opt/myjob/share/perl5/site_perl/5.32/bin/perltidy`.

**Comment by Grinnz** [comment]
Scripts are actually installed to installsitescript by default but both should generally be set to the same thing. You might want to read the section at https://github.com/Perl/perl5/blob/blead/INSTALL#L593 carefully. You should be setting "prefix" when configuring Perl to indicate where you're installing it to, and all of the default install locations are based on that. If you want site installed modules (manually installed from CPAN) to use a different prefix you can set "siteprefix" separately. Or if you want scripts to go somewhere specific not based on that prefix, you would set "sitescript" and "sitebin".

**Comment by Leont** [comment]
I can see why you would want that, but suddenly introducing such behavior, even if it's just an option, will break things because often scripts (and tests) assume the name is unversioned.

Like Grinnz said, you probably shouldn't be installing scripts from different perls to the same directory.

**Comment by matthewpersico** [comment]
Sorry I haven't been following - my son, a police officer, finally got COVID and now I have it so I've been a bit under the weather.

I realize now that there are some details about how we install software at my $ that I didn't mention and I am not sure I should - IP and all that.

Suffice to say I am going to rebuild all Perls with INSTALLSITEBIN ne INSTALLBIN. (I've been installing Perl for 20+years and TIL...) This will allow me to have multiple versions of Perl side by side on a machine for testing without having their scripts (and altered shebangs) stepping all over each other. In our install system, I can arrange for "script" to be linked to /opt/myjob/bin/script.PerlVersion. And when I am testing, I can also have /opt/myjob/bin/script link to  /opt/myjob/bin/script.PerlVersionIAmTesting. Which also allows me to have an upgraded version of the module installed for the upgrading Perl.

Yeah it seems complicated, but its the most flexible arrangement just in case I end up with side by side Perls on a production machine with a gradual cutover. Don't think it will happen, but I prefer to be prepared Just In Case.

Thank you all for your input.

**Comment by Grinnz** [comment]
Hope that you and your son recover quickly. I'm going to close this as any solution to this on the tooling side would be unnecessarily complex, but `#toolchain` on irc.perl.org is happy to help with any such CPAN configuration and installation engineering.
