### ISSUE TITLE
Change in VERSION_FROM behavior (v7.58)

### ISSUE THREAD

**Issue by pryrt** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#388]
I have a module which builds just fine when I use ExtUtils::MakeMaker v7.36 (with strawberry perl 5.30.0).
But if I upgrade to ExtUtils::MakeMaker v7.58, I get the warning

```
WARNING: Setting VERSION via file 'lib/Win32/Mechanize/NotepadPlusPlus.pm' failed
 at C:/usr/local/apps/berrybrew/perls/xsys/perl/site/lib/ExtUtils/MakeMaker.pm line 741.
```

I actually first saw it when running CI on my project, where I happened to re-run the CI on the same commit:
* https://ci.appveyor.com/project/pryrt/win32-mechanize-notepadplusplus/builds/37437896/job/p7d30y8g1yxv5j22#L114 uses strawberry-perl 5.32.0.1 with EU::MM v7.46, and does not show the warning
* https://ci.appveyor.com/project/pryrt/win32-mechanize-notepadplusplus/builds/37530479/job/bu2qvgk8b48l90gd#L113 uses strawberry-perl 5.32.1.1 with EU::MM v7.58, which does show the warning

so it was working the old way as recently as v7.46.  I did not bisect any farther to find out exactly which version between v7.46 and v7.58 caused the change in behavior

Making an SSCCE:

Makefile.PL:
```
use ExtUtils::MakeMaker;
use 5.010;

WriteMakefile(
    'NAME'          => 'blah',
    'VERSION_FROM'  => 'blah.pm',
);
```

blah.pm:
```
package blah;
use warnings;
use strict;
use 5.010;

our $VERSION = '0.006dbg';  # rrr.mmmsss : rrr is major revision; mmm is minor revision; sss is sub-revision (new feature path or bugfix); optionally use _sss instead, for alpha sub-releases

1;
```

If you run `perl Makefile.PL` on the above with EU::MM v7.36, it works just fine.  If you run it with EU::MM v7.58, it gives the warning
```
WARNING: Setting VERSION via file 'blah.pm' failed
 at C:/usr/local/apps/berrybrew/perls/xsys/perl/site/lib/ExtUtils/MakeMaker.pm line 741.
```
If I change the line to 
```
our $VERSION = '0.006';  # rrr.mmmsss : rrr is major revision; mmm is minor revision; sss is sub-revision (new feature path or bugfix); optionally use _sss instead, for alpha sub-releases
```
it will work without warning on either.

So there is a change in behavior.  If this behavior was intended; fine.  But in case it was unintentional, I thought I would point it out.

**Comment by pryrt** [comment]
I am willing to admit that having "dbg" in the VERSION string is non-standard (and when I release, it won't be in there), but it's something I've done to indicate debugging version before I'm ready for release.  if that's unsupported, fine.

**Comment by Grinnz** [comment]
It is unsupported. $VERSION must only contain digits, dots, underscores, and an optional leading v.

**Comment by Grinnz** [comment]
See http://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html for further reading on how Perl module versions work.

**Comment by pryrt** [comment]
Like I said, when I release, I don't include the text; it had just always worked without warning every time I'd used that as a temporary indicator, but started warning in v7.58.  But since it's not supported, I'll close the issue.

**Comment by Grinnz** [comment]
FWIW, this is likely the commit that started reporting this to the user as an issue. https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/commit/65a78780d42e4e11c57fb39d2a1078792a68ed8a

**Comment by Grinnz** [comment]
And the referenced ticket. https://rt.cpan.org/Public/Bug/Display.html?id=132875

**Comment by pryrt** [comment]
BTW: thank you for replying so quickly.  Such quick support is appreciated
