### ISSUE TITLE
Latest EU::MM fails on perl 5.12 and below when JSON::PP 4.08 is installed

### ISSUE THREAD

**Issue by DrHyde** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#416]
[This change](https://github.com/makamaka/JSON-PP/commit/9b65333d1a5bde3d13060121e85c5c234e01030b#diff-8eae66db42fb29ffa131a180d7e8c9b771d4717c9877ba1fda72cfd3d923afbfR1256) in [JSON::PP](https://github.com/makamaka/JSON-PP/), first released in JSON::PP 4.08, seems to cause extra warnings on Ye Olde Perle, which in turn cause EU::MM to [fail several of its tests](https://github.com/DrHyde/perl-modules-lib-relative-to/runs/6427981248?check_suite_focus=true#step:4:176), such as:

```
t/min_perl_version.t ...... 1/35
#   Failed test 'MIN_PERL_VERSION=5 does not trigger a warning'
#   at t/min_perl_version.t line 90.
#          got: 'Unicode non-character 0x10ffff is illegal for interchange at /Users/david/perl5/perlbrew/perls/perl-5.12.5/lib/site_perl/5.12.5/JSON/PP.pm line 1276.
# '
#     expected: ''
t/min_perl_version.t ...... 30/35 # Looks like you failed 1 test of 35.
t/min_perl_version.t ...... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/35 subtests
```

This only happens for perl 5.12 and below with JSON::PP 4.08 and above. Later perls are fine with an up-to-date JSON::PP, and 5.12 is fine with JSON::PP 4.07.

I've not tested any perl older than 5.12.5, but [the failures spat out in my CI for 5.10 and 5.8](https://github.com/DrHyde/perl-modules-lib-relative-to/runs/6427771394?check_suite_focus=true#step:4:191) look the same

**Comment by DrHyde** [comment]
Mentioning @makamaka so he is aware

**Comment by haarg** [comment]
makamaka/JSON-PP#68 should fix this

**Comment by DrHyde** [comment]
Yep, EU::MM on Ye Olde Perle passes its tests when JSON::PP 4.09 is installed.
