### ISSUE TITLE
Module inter dependence

### ISSUE THREAD

**Issue by YaoMingYa** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#420]
#perl  Makefile.pl
"perl  Makefile.pl "  warn "can not locate lib.pm ",also when I download and tar lib.tar ,then "perl Makefile.pl" warning looks like "can not locate ExtUtils :: MakeMaker.pm"

**Comment by Grinnz** [comment]
You need to use a CPAN client to properly install modules and their dependencies. See https://www.cpan.org/modules/INSTALL.html
