### ISSUE TITLE
Cygwin ci failure "fatal: detected dubious ownership in repository"

### ISSUE THREAD

**Issue by demerphq** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#428]
There seems to be an issue with the cygwin CI pipeline tests. 

See: https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/actions/runs/4149341727/jobs/7178212414 

```
Run path c:\tools\cygwin\bin;c:\tools\cygwin\usr\bin
error: could not lock config file /home/runneradmin/.gitconfig: No such file or directory
fatal: detected dubious ownership in repository at '/cygdrive/d/a/ExtUtils-MakeMaker/ExtUtils-MakeMaker'
To add an exception for this directory, call:

	git config --global --add safe.directory /cygdrive/d/a/ExtUtils-MakeMaker/ExtUtils-MakeMaker
```

**Comment by Leont** [comment]
Yeah, this has been broken for a while now. The solution isn't obvious to me either.

**Comment by demerphq** [comment]
Can we not just do what they suggest and add

```
git config --global --add safe.directory /cygdrive/d/a/ExtUtils-MakeMaker/ExtUtils-MakeMaker
```
to the setup recipe?

**Comment by demerphq** [comment]
I guess not. See https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/429

I tried setting it up very early. But nope, no joy.

**Comment by perlpunk** [comment]
I tried `git config --system` and this works, see #430
