### ISSUE TITLE
release status of -TRIAL release could be either "unstable" or "testing"

### ISSUE THREAD

**Issue by XSven** [Perl-Toolchain-Gang/ExtUtils-MakeMaker#458]
I guess the new EU:MM development release 7.71_01 was inspired by https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/455. If I read the changes item

> Set META status as "unstable" for -TRIAL releases

correctly a -TRIAL release has now a hardcoded release status "unstable".  Remembering the [comment](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/455#issuecomment-2166176393) made by @Grinnz the release status of a -TRIAL release could be either "unstable" or "testing". Please explain this contradiction.

**Comment by Grinnz** [comment]
This is the same action as when the version contains an underscore. Authoring tools (of which EUMM is grudgingly one) must decide what release_status to set when told to make a trial release; EUMM decided to set "unstable" and Dist::Zilla decided to set "testing". Fortunately no tools seem to make any useful distinction between these anyway.
